---
title: "Computational Enhancement of `rpwexp` "
author: "Jianxiao Yang"
output:
  html_document:
    code_folding: hide
    toc: TRUE
    toc_float: TRUE
    number_sections: true
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(simtrial)
library(knitr)
library(tibble)
library(dplyr)
library(gt)
library(profvis)
library(bench)
devtools::load_all()
```


# Data

In this example, we consider

- 7 strata
- 10 periods in enrollments
- 4 periods in failure rates of the control arm per stratum
- 5 periods in failure rates of the experimental arm per stratum
- 4 periods in dropout rates of the control arm per stratum
- 5 periods in dropout rates of the experimental arm per stratum

```{r}
# 1.1 Set up Strata & Block
strata <- tibble(
  Stratum = c("A", "B", "C", "D", "E", "F", "G"), 
  p = c(rep(0.1, 4), rep(0.2, 3)))
  
block <- c(rep("Control", 2), rep("Experimental", 2))

# 1.2 Set up Enrollment Rates
enrollRates <- bind_rows(
   # control arm - low stratum - 4 periods
   tibble(period = 1,  duration = 2, rate = 9),
   tibble(period = 2,  duration = 3, rate = 10),
   tibble(period = 3,  duration = 4, rate = 11),
   tibble(period = 4,  duration = 5, rate = 12),
   tibble(period = 5,  duration = 2, rate = 5),
   tibble(period = 6,  duration = 1, rate = 6),
   tibble(period = 7,  duration = 3, rate = 7),
   tibble(period = 8,  duration = 2, rate = 8),
   tibble(period = 9,  duration = 2, rate = 4),
   tibble(period = 10, duration = 1, rate = 2)
)

# 1.3 Set up Failure Rates
failRates <- bind_rows(
   # stratum A 
   tibble(Stratum = "A" , period = 1, Treatment = "Control"     , duration = 3, rate = .03),
   tibble(Stratum = "A" , period = 2, Treatment = "Control"     , duration = 2, rate = .04),
   tibble(Stratum = "A" , period = 3, Treatment = "Control"     , duration = 1, rate = .05),
   tibble(Stratum = "A" , period = 4, Treatment = "Control"     , duration = 2, rate = .06),
   tibble(Stratum = "A" , period = 1, Treatment = "Experimental", duration = 2, rate = .03),
   tibble(Stratum = "A" , period = 2, Treatment = "Experimental", duration = 3, rate = .04),
   tibble(Stratum = "A" , period = 3, Treatment = "Experimental", duration = 1, rate = .05),
   tibble(Stratum = "A" , period = 4, Treatment = "Experimental", duration = 2, rate = .06),
   tibble(Stratum = "A" , period = 5, Treatment = "Experimental", duration = 3, rate = .07),
   
   # stratum B 
   tibble(Stratum = "B", period = 1, Treatment = "Control"     , duration = 3, rate = .05),
   tibble(Stratum = "B", period = 2, Treatment = "Control"     , duration = 2, rate = .06),
   tibble(Stratum = "B", period = 3, Treatment = "Control"     , duration = 2, rate = .07),
   tibble(Stratum = "B", period = 4, Treatment = "Control"     , duration = 1, rate = .08),
   tibble(Stratum = "B", period = 1, Treatment = "Experimental", duration = 4, rate = .06),
   tibble(Stratum = "B", period = 2, Treatment = "Experimental", duration = 3, rate = .07),
   tibble(Stratum = "B", period = 3, Treatment = "Experimental", duration = 2, rate = .08),
   tibble(Stratum = "B", period = 4, Treatment = "Experimental", duration = 2, rate = .09),
   tibble(Stratum = "B", period = 5, Treatment = "Experimental", duration = 1, rate = .095),
   
   # stratum C
   tibble(Stratum = "C", period = 1, Treatment = "Control"     , duration = 4, rate = .01),
   tibble(Stratum = "C", period = 2, Treatment = "Control"     , duration = 2, rate = .02),
   tibble(Stratum = "C", period = 3, Treatment = "Control"     , duration = 3, rate = .025),
   tibble(Stratum = "C", period = 4, Treatment = "Control"     , duration = 1, rate = .022),
   tibble(Stratum = "C", period = 1, Treatment = "Experimental", duration = 3, rate = .011),
   tibble(Stratum = "C", period = 2, Treatment = "Experimental", duration = 2, rate = .014),
   tibble(Stratum = "C", period = 3, Treatment = "Experimental", duration = 1, rate = .012),
   tibble(Stratum = "C", period = 4, Treatment = "Experimental", duration = 3, rate = .02),
   tibble(Stratum = "C", period = 5, Treatment = "Experimental", duration = 2, rate = .022),
   
   # stratum D
   tibble(Stratum = "D", period = 1, Treatment = "Control"     , duration = 3, rate = .02),
   tibble(Stratum = "D", period = 2, Treatment = "Control"     , duration = 2, rate = .022),
   tibble(Stratum = "D", period = 3, Treatment = "Control"     , duration = 1, rate = .018),
   tibble(Stratum = "D", period = 4, Treatment = "Control"     , duration = 1, rate = .024),
   tibble(Stratum = "D", period = 1, Treatment = "Experimental", duration = 4, rate = .017),
   tibble(Stratum = "D", period = 2, Treatment = "Experimental", duration = 2, rate = .024),
   tibble(Stratum = "D", period = 3, Treatment = "Experimental", duration = 3, rate = .022),
   tibble(Stratum = "D", period = 4, Treatment = "Experimental", duration = 1, rate = .026),
   tibble(Stratum = "D", period = 5, Treatment = "Experimental", duration = 2, rate = .02),
   
   # stratum E
   tibble(Stratum = "E", period = 1, Treatment = "Control"     , duration = 1, rate = .05),
   tibble(Stratum = "E", period = 2, Treatment = "Control"     , duration = 2, rate = .045),
   tibble(Stratum = "E", period = 3, Treatment = "Control"     , duration = 2, rate = .052),
   tibble(Stratum = "E", period = 4, Treatment = "Control"     , duration = 4, rate = .04),
   tibble(Stratum = "E", period = 1, Treatment = "Experimental", duration = 2, rate = .06),
   tibble(Stratum = "E", period = 2, Treatment = "Experimental", duration = 3, rate = .065),
   tibble(Stratum = "E", period = 3, Treatment = "Experimental", duration = 3, rate = .058),
   tibble(Stratum = "E", period = 4, Treatment = "Experimental", duration = 2, rate = .062),
   tibble(Stratum = "E", period = 5, Treatment = "Experimental", duration = 2, rate = .064),

   # stratum F
   tibble(Stratum = "F", period = 1, Treatment = "Control"     , duration = 2, rate = .052),
   tibble(Stratum = "F", period = 2, Treatment = "Control"     , duration = 3, rate = .053),
   tibble(Stratum = "F", period = 3, Treatment = "Control"     , duration = 3, rate = .054),
   tibble(Stratum = "F", period = 4, Treatment = "Control"     , duration = 4, rate = .055),
   tibble(Stratum = "F", period = 1, Treatment = "Experimental", duration = 3, rate = .054),
   tibble(Stratum = "F", period = 2, Treatment = "Experimental", duration = 2, rate = .055),
   tibble(Stratum = "F", period = 3, Treatment = "Experimental", duration = 2, rate = .056),
   tibble(Stratum = "F", period = 4, Treatment = "Experimental", duration = 1, rate = .057),
   tibble(Stratum = "F", period = 5, Treatment = "Experimental", duration = 4, rate = .058),
   
   # stratum G
   tibble(Stratum = "G", period = 1, Treatment = "Control"     , duration = 1, rate = .04),
   tibble(Stratum = "G", period = 2, Treatment = "Control"     , duration = 2, rate = .042),
   tibble(Stratum = "G", period = 3, Treatment = "Control"     , duration = 3, rate = .044),
   tibble(Stratum = "G", period = 4, Treatment = "Control"     , duration = 4, rate = .048),
   tibble(Stratum = "G", period = 1, Treatment = "Experimental", duration = 4, rate = .05),
   tibble(Stratum = "G", period = 2, Treatment = "Experimental", duration = 2, rate = .053),
   tibble(Stratum = "G", period = 3, Treatment = "Experimental", duration = 3, rate = .056),
   tibble(Stratum = "G", period = 4, Treatment = "Experimental", duration = 1, rate = .057),
   tibble(Stratum = "G", period = 5, Treatment = "Experimental", duration = 3, rate = .058)
)

# 1.4 Set up Dropout Rates
dropoutRates <- bind_rows(
   # stratum A
   tibble(Stratum = "A" , period = 1, Treatment = "Control"     , duration = 3, rate = .001),
   tibble(Stratum = "A" , period = 2, Treatment = "Control"     , duration = 2, rate = .002),
   tibble(Stratum = "A" , period = 3, Treatment = "Control"     , duration = 3, rate = .0015),
   tibble(Stratum = "A" , period = 4, Treatment = "Control"     , duration = 3, rate = .0022),
   tibble(Stratum = "A" , period = 1, Treatment = "Experimental", duration = 2, rate = .001),
   tibble(Stratum = "A" , period = 2, Treatment = "Experimental", duration = 2, rate = .0015),
   tibble(Stratum = "A" , period = 3, Treatment = "Experimental", duration = 2, rate = .0009),
   tibble(Stratum = "A" , period = 4, Treatment = "Experimental", duration = 4, rate = .0008),
   tibble(Stratum = "A" , period = 5, Treatment = "Experimental", duration = 4, rate = .0007),
   
   # stratum B
   tibble(Stratum = "B", period = 1, Treatment = "Control"     , duration = 3, rate = .0008),
   tibble(Stratum = "B", period = 2, Treatment = "Control"     , duration = 1, rate = .0009),
   tibble(Stratum = "B", period = 3, Treatment = "Control"     , duration = 1, rate = .001),
   tibble(Stratum = "B", period = 4, Treatment = "Control"     , duration = 2, rate = .0011),
   tibble(Stratum = "B", period = 1, Treatment = "Experimental", duration = 3, rate = .0009),
   tibble(Stratum = "B", period = 2, Treatment = "Experimental", duration = 4, rate = .0008),
   tibble(Stratum = "B", period = 3, Treatment = "Experimental", duration = 4, rate = .0011),
   tibble(Stratum = "B", period = 4, Treatment = "Experimental", duration = 2, rate = .0012),
   tibble(Stratum = "B", period = 5, Treatment = "Experimental", duration = 3, rate = .0007),
   
   # stratum C
   tibble(Stratum = "C", period = 1, Treatment = "Control"     , duration = 3, rate = .0011),
   tibble(Stratum = "C", period = 2, Treatment = "Control"     , duration = 4, rate = .0012),
   tibble(Stratum = "C", period = 3, Treatment = "Control"     , duration = 2, rate = .0013),
   tibble(Stratum = "C", period = 4, Treatment = "Control"     , duration = 1, rate = .0014),
   tibble(Stratum = "C", period = 1, Treatment = "Experimental", duration = 2, rate = .001),
   tibble(Stratum = "C", period = 2, Treatment = "Experimental", duration = 3, rate = .0009),
   tibble(Stratum = "C", period = 3, Treatment = "Experimental", duration = 3, rate = .0008),
   tibble(Stratum = "C", period = 4, Treatment = "Experimental", duration = 1, rate = .0007),
   tibble(Stratum = "C", period = 5, Treatment = "Experimental", duration = 3, rate = .0006),
   
   # stratum D
   tibble(Stratum = "D", period = 1, Treatment = "Control"     , duration = 2, rate = .0015),
   tibble(Stratum = "D", period = 2, Treatment = "Control"     , duration = 3, rate = .0012),
   tibble(Stratum = "D", period = 3, Treatment = "Control"     , duration = 1, rate = .0013),
   tibble(Stratum = "D", period = 4, Treatment = "Control"     , duration = 4, rate = .0014),
   tibble(Stratum = "D", period = 1, Treatment = "Experimental", duration = 3, rate = .002),
   tibble(Stratum = "D", period = 2, Treatment = "Experimental", duration = 2, rate = .0018),
   tibble(Stratum = "D", period = 3, Treatment = "Experimental", duration = 1, rate = .0017),
   tibble(Stratum = "D", period = 4, Treatment = "Experimental", duration = 1, rate = .0015),
   tibble(Stratum = "D", period = 5, Treatment = "Experimental", duration = 5, rate = .0016),
   
   # stratum E
   tibble(Stratum = "E", period = 1, Treatment = "Control"     , duration = 3, rate = .0005),
   tibble(Stratum = "E", period = 2, Treatment = "Control"     , duration = 2, rate = .0008),
   tibble(Stratum = "E", period = 3, Treatment = "Control"     , duration = 2, rate = .0009),
   tibble(Stratum = "E", period = 4, Treatment = "Control"     , duration = 2, rate = .001),
   tibble(Stratum = "E", period = 1, Treatment = "Experimental", duration = 3, rate = .001),
   tibble(Stratum = "E", period = 2, Treatment = "Experimental", duration = 1, rate = .0012),
   tibble(Stratum = "E", period = 3, Treatment = "Experimental", duration = 1, rate = .0013),
   tibble(Stratum = "E", period = 4, Treatment = "Experimental", duration = 4, rate = .0011),
   tibble(Stratum = "E", period = 5, Treatment = "Experimental", duration = 1, rate = .0015),
   
   # stratum F
   tibble(Stratum = "F", period = 1, Treatment = "Control"     , duration = 3, rate = .0008),
   tibble(Stratum = "F", period = 2, Treatment = "Control"     , duration = 2, rate = .0009),
   tibble(Stratum = "F", period = 3, Treatment = "Control"     , duration = 1, rate = .001),
   tibble(Stratum = "F", period = 4, Treatment = "Control"     , duration = 2, rate = .0012),
   tibble(Stratum = "F", period = 1, Treatment = "Experimental", duration = 2, rate = .0007),
   tibble(Stratum = "F", period = 2, Treatment = "Experimental", duration = 3, rate = .0009),
   tibble(Stratum = "F", period = 3, Treatment = "Experimental", duration = 3, rate = .001),
   tibble(Stratum = "F", period = 4, Treatment = "Experimental", duration = 1, rate = .0012),
   tibble(Stratum = "F", period = 5, Treatment = "Experimental", duration = 4, rate = .0011),
   
   # stratum G
   tibble(Stratum = "G", period = 1, Treatment = "Control"     , duration = 4, rate = .0011),
   tibble(Stratum = "G", period = 2, Treatment = "Control"     , duration = 1, rate = .0012),
   tibble(Stratum = "G", period = 3, Treatment = "Control"     , duration = 2, rate = .0009),
   tibble(Stratum = "G", period = 4, Treatment = "Control"     , duration = 1, rate = .001),
   tibble(Stratum = "G", period = 1, Treatment = "Experimental", duration = 4, rate = .001),
   tibble(Stratum = "G", period = 2, Treatment = "Experimental", duration = 2, rate = .0012),
   tibble(Stratum = "G", period = 3, Treatment = "Experimental", duration = 3, rate = .0013),
   tibble(Stratum = "G", period = 4, Treatment = "Experimental", duration = 3, rate = .001),
   tibble(Stratum = "G", period = 5, Treatment = "Experimental", duration = 2, rate = .0012)
)

```


# Profile `rpwexp`
```{r}
n <- 1000
x <- tibble(Stratum = sample(x = strata$Stratum, size = n, replace = TRUE, prob = strata$p)) %>%
  mutate(enrollTime = rpwenroll(n, enrollRates)) %>%
  group_by(Stratum) %>% 
  mutate(Treatment = fixedBlockRand(n = n(), block = block))  %>%
  group_by(Stratum, Treatment)

utr <- unique(x$Treatment)
usr <- unique(x$Stratum)
x$failTime <- 0
x$dropoutTime <- 0

# # Reorder x, failRates, and dropoutRates
# x1 <- x %>% arrange(Stratum, Treatment)
# failRates1 <- failRates %>% arrange(Stratum, Treatment)
# dropoutRates1 <- dropoutRates %>% arrange(Stratum, Treatment)
# utr <- unique(x1$Treatment)
# usr <- unique(x1$Stratum)
```

## R
```{r}
set.seed(2022)
profvis({
  for(sr in usr){for(tr in utr){
      indx <- x$Stratum==sr & x$Treatment==tr
      x$failTime[indx] <- rpwexp(n=sum(indx),failRates=filter(failRates,Stratum==sr&Treatment==tr))
      x$dropoutTime[indx] <- rpwexp(n=sum(indx),failRates=filter(dropoutRates,Stratum==sr&Treatment==tr))
  }}
})
```

## C++
```{r}
profvis({
  for(sr in usr){for(tr in utr){
      indx <- x$Stratum==sr & x$Treatment==tr
      x$failTime[indx] <- rpwexpRcpp(n=sum(indx),failRates=filter(failRates,Stratum==sr&Treatment==tr))
      x$dropoutTime[indx] <- rpwexpRcpp(n=sum(indx),failRates=filter(dropoutRates,Stratum==sr&Treatment==tr))
  }}
})
```


# Benchmark `rpwexp`
```{r}
n <- 1000
x <- tibble(Stratum = sample(x = strata$Stratum, size = n, replace = TRUE, prob = strata$p)) %>%
  mutate(enrollTime = rpwenroll(n, enrollRates)) %>%
  group_by(Stratum) %>% 
  mutate(Treatment = fixedBlockRand(n = n(), block = block))  %>%
  group_by(Stratum, Treatment)

utr <- unique(x$Treatment)
usr <- unique(x$Stratum)
x$failTime <- 0
x$dropoutTime <- 0

sr <- usr[1]
tr <- utr[1]
indx <- x$Stratum==sr & x$Treatment==tr

set.seed(2022)
mbm <- bench::mark(
  # R
  rpwexp(n=sum(indx),failRates=filter(failRates,Stratum==sr&Treatment==tr)),
  # C++
  rpwexpRcpp(n=sum(indx),failRates=filter(failRates,Stratum==sr&Treatment==tr)),
  iterations = 100
)
mbm$expression[[1]] <- "R"
mbm$expression[[2]] <- "C++"
print(mbm %>% select(c("expression", "min", "median", "mem_alloc", "gc/sec", "n_itr", "n_gc", "total_time")), n = 10)
# plot(mbm)
```

