---
title: "Benchmark Example for `simfix`"
author: "Jianxiao Yang"
output:
  html_document:
    code_folding: hide
    toc: TRUE
    toc_float: TRUE
    number_sections: true
---

```{r}
sessionInfo()
```

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(simtrial)
library(knitr)
library(tibble)
library(dplyr)
library(gt)
library(ggplot2)
library(profvis)
library(bench)
library(microbenchmark)
library(PWEALL)
library(parallel)
devtools::load_all()
```

# Data

In this example, we consider

- 2 strata
- 2 periods in enrollments
- 4 periods in failure rates of the control arm per stratum
- 4 periods in failure rates of the experimental arm per stratum
- 4 periods in dropout rates of the control arm per stratum
- 4 periods in dropout rates of the experimental arm per stratum

```{r}
# 2 strata: Biomarker negative (50% of population) + Biomarker positive (50% of population); 
strata <- tibble(Stratum = c("Biomarker Negative", "Biomarker Positive"), p = c(.5, .5))

block <- c(rep("Control", 2), rep("Experimental", 2))

# enrollment over 1 year, with ramp-up over first 6 months
enrollRates <- tibble(rate = c(9, 2), duration = c(6, 6))

# failure rate:
# - biomarker negative: control is exponential with median of 12 months; experimental has HR = 1.2 for 4 months followed by HR=.65
# - biomarker positive: control is exponential with median of 12 months; experimental has HR = .9 for 4 months followed by HR=.4)
failRates <- tibble(
  Stratum = c(rep("Biomarker Negative", 3), rep("Biomarker Positive", 3)),
  period = c(1, 1:2, 1, 1:2),
  Treatment = rep(c("Control", rep("Experimental", 2)), 2),
  duration = c(12, 4, 8, 12, 4, 8), 
  rate = c(log(2)/12, log(2)/12*1.2, log(2)/12*0.65, log(2)/12, log(2)/12*0.9, log(2)/12*0.4)
)

# dropout rate
dropoutRates <- tibble(
  Stratum = c(rep("Biomarker Negative", 4), rep("Biomarker Positive", 4)),
  period = rep(1:2, 4),
  Treatment = rep(c(rep("Control", 2), rep("Experimental", 2)), 2),
  duration = rep(c(3, 1), 4),
  rate = rep(c(.001, .001), 4)
)

# Create failRatesAll for simfix
failRatesAll <- failRates[failRates$Treatment == "Experimental", ]
failRatesAll$dropoutRate <- dropoutRates[dropoutRates$Treatment == "Experimental", ]$rate
failRatesAll$hr <- c(rep(0.6, 2), rep(0.9, 2))
failRatesAll <- failRatesAll %>%
  mutate(failRate = rate/hr) %>%
  select("Stratum", "duration", "failRate", "hr", "dropoutRate")
rg <- tibble(rho = 0, gamma = 0)
```

# 10000 simulations
```{r}
system.time(
    simfix(
    nsim = 10000, # Number of simulations
    sampleSize = 800, # Trial sample size
    targetEvents = 350, # Targeted events at analysis
    strata = strata, # Study strata
    enrollRates = enrollRates, # Enrollment rates
    failRates = failRatesAll, # Failure rates
    totalDuration = 30, # Planned trial duration
    block = block, # Block for treatment
    timingType = 1:5, # Use all possible data cutoff methods
    rg = rg # FH test(s) to use; in this case, logrank
  )
)

system.time(
  simfixNew(
    nsim = 10000, # Number of simulations
    sampleSize = 800, # Trial sample size
    targetEvents = 350, # Targeted events at analysis
    strata = strata, # Study strata
    enrollRates = enrollRates, # Enrollment rates
    failRates = failRatesAll, # Failure rates
    totalDuration = 30, # Planned trial duration
    block = block, # Block for treatment
    timingType = 1:5, # Use all possible data cutoff methods
    rg = rg # FH test(s) to use; in this case, logrank
  )
)
```
