#  Copyright (c) 2022 Merck & Co., Inc., Rahway, NJ, USA and its affiliates. All rights reserved.
#
#  This file is part of the simtrial program.
#
#  simtrial is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#' Cut a Dataset for Analysis at a Specified Event Count
#'
#' `cutDataAtCount` takes a time-to-event data set and cuts the data at which an
#' event count is reached.
#'
#' @param x a time-to-event dataset, e.g., generated by \code{simPWSurv}
#' @param count event count at which data cutoff is to be made
#'
#' @examples
#' library(tidyr)
#' # Use default enrollment and event rates at cut at 100 events
#' x <- simPWSurv(n = 200) %>% cutDataAtCount(100)
#' table(x$event, x$Treatment)
#'
#' @return a \code{tibble} ready for survival analysis, including culumns time to event (`tte`),
#' `event`, the `stratum` and the `treatment.`
#'
#' @export

cutDataAtCount <- function(x, count){
  cut_date <- getCutDateForCount(x, count)
  ans <- x %>% cutData(cutDate = cut_date)

  return(ans)
}
