# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The piecewise exponential distribution in C++
#'
#' @param n Number of observations to be generated.
#' @param fail_rate A data frame containing `duration` and `rate` variables.
#'
#' @export
rpwexpRcpp <- function(n, fail_rate) {
    .Call(`_simtrial_rpwexpRcpp`, n, fail_rate)
}

#' The piecewise exponential distribution using inverse CDF method in C++
#'
#' @param n Number of observations to be generated.
#' @param fail_rate A data frame containing `duration` and `rate` variables.
#'
#' @export
rpwexpinvRcpp <- function(n, fail_rate) {
    .Call(`_simtrial_rpwexpinvRcpp`, n, fail_rate)
}

