# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The Piecewise Exponential Distribution in C++
#'
#' @param n Number of observations to be generated.
#' @param fail_rate A dataframe containing \code{duration} and \code{rate} variables.
#' @export
rpwexpRcpp <- function(n, fail_rate) {
    .Call(`_simtrial_rpwexpRcpp`, n, fail_rate)
}

#' The Piecewise Exponential Distribution using inverse CDF method in C++
#'
#' @param n Number of observations to be generated.
#' @param fail_rate A dataframe containing \code{duration} and \code{rate} variables.
#' @export
rpwexpinvRcpp <- function(n, fail_rate) {
    .Call(`_simtrial_rpwexpinvRcpp`, n, fail_rate)
}

