# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Piecewise exponential distribution using the inverse CDF method
#'
#' @param n Number of observations to be generated.
#' @param fail_rate A data frame containing `duration` and `rate` variables.
#'
rpwexp_inverse_cdf_cpp <- function(n, fail_rate) {
    .Call(`_simtrial_rpwexp_inverse_cdf_cpp`, n, fail_rate)
}

#' Piecewise exponential distribution using the naive method
#'
#' @param n Number of observations to be generated.
#' @param fail_rate A data frame containing `duration` and `rate` variables.
#'
rpwexp_naive_cpp <- function(n, fail_rate) {
    .Call(`_simtrial_rpwexp_naive_cpp`, n, fail_rate)
}

