#  Copyright (c) 2023 Merck & Co., Inc., Rahway, NJ, USA and its affiliates.
#  All rights reserved.
#
#  This file is part of the simtrial program.
#
#  simtrial is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#' Weighted logrank test
#'
#' @param data cutted dataset generated by sim_pw_surv
#' @param weight weighting functions, such as \code{fh_weight}, \code{mb_weight}, and \code{early_zero_weight}.
#'
#' @return test results
#' @export
#' @examples
#' sim_pw_surv(n = 200) |>
#'   cut_data_by_event(150) |>
#'   wlr(weight = fh(rho = 0, gamma = 0))
#'
#' sim_pw_surv(n = 200) |>
#'   cut_data_by_event(150) |>
#'   wlr(weight = mb(delay = 4, w_max = 2))
#'
#' sim_pw_surv(n = 200) |>
#'   cut_data_by_event(150) |>
#'   wlr(weight = early_zero(early_period = 4))
#'
wlr <- function(data, weight){

  if ("fh" %in% class(weight)) {
    ans <- data |>
      counting_process(arm = "experimental") |>
      fh_weight(rho_gamma = data.frame(rho = weight$rho, gamma = weight$gamma))

  } else if ("mb" %in% class(weight)) {
    ans <- data |>
      counting_process(arm = "experimental") |>
      mb_weight(delay = weight$delay, w_max = weight$w_max) |>
      dplyr::summarize(
        s = sum(o_minus_e * mb_weight),
        v = sum(var_o_minus_e * mb_weight^2),
        z = s / sqrt(v)) |>
      dplyr::select(z)
  } else if ("early_period" %in% class(weight)){
    ans <- data |>
      counting_process(arm = "experimental") |>
      early_zero_weight(early_period = weight$early_period) |>
      dplyr::summarize(
        s = sum(o_minus_e * weight),
        v = sum(var_o_minus_e * weight^2),
        z = s / sqrt(v)) |>
      dplyr::select(z)
  }
  return(ans)
}
